// title = Human-readable name of the vanilla item in the location
// id = Internal ID of the vanilla item in the location
// top = Distance in map grid from top, multiplied by 'mapGridSize' in tracker.js to get absolute pixel position
// left = Distance in map grid from left, multiplied by 'mapGridSize' in tracker.js to get absolute pixel position

const itemData = [
    {
		title: "Axiom Disruptor",
        id: "DataDisruptor",
        top: 43,
        left: 7,
    },
    {
		title: "Nova",
        id: "Nova",
        top: 36,
        left: 17,
    },
    {
		title: "Size Node 1",
        id: "SizeNode1",
        top: 39,
        left: 9,
    },
    {
		title: "Laser Drill",
        id: "Drill",
        top: 41,
        left: 17,
    },
    {
		title: "Power Node 1",
        id: "PowerNode1",
        top: 42,
        left: 15,
    },
    {
		title: "Multi-Disruptor",
        id: "MultiDisruptor",
        top: 37,
        left: 10,
    },
    {
		title: "Health Node 1",
        id: "HealthNode1",
        top: 50,
        left: 16,
    },
    {
		title: "Health Node Fragment 2",
        id: "HealthNodeFragment2",
        top: 49,
        left: 13,
    },
    {
		title: "Health Node Fragment 13",
        id: "HealthNodeFragment13",
        top: 43,
        left: 3,
    },
    {
		title: "Health Node Fragment 16",
        id: "PowerNodeFragment16",
        top: 48,
        left: 16,
    },
    {
		title: "Health Node 9",
        id: "HealthNode9",
        top: 34,
        left: 15,
    },
    {
		title: "Lightning Gun",
        id: "LightningGun",
        top: 45,
        left: 11,
    },
    {
		title: "Faded Note",
        id: "Note2",
        top: 41,
        left: 9,
    },
    {
		title: "Orbital Discharge",
        id: "WallTrace",
        top: 47,
        left: 12,
    },
    {
		title: "Power Node Fragment 2",
        id: "PowerNodeFragment2",
        top: 37,
        left: 7,
    },
    {
		title: "Flamethrower",
        id: "FlameThrower",
        top: 38,
        left: 3,
    },
    {
		title: "Health Node Fragment 1",
        id: "HealthNodeFragment1",
        top: 57,
        left: 17,
    },
    {
		title: "Kilver",
        id: "Kilver",
        top: 59,
        left: 21,
    },
    {
		title: "Health Node Fragment 4",
        id: "HealthNodeFragment4",
        top: 54,
        left: 19,
    },
    {
		title: "Address Disruptor 1",
        id: "AddressDisruptor1",
        top: 57,
        left: 26,
    },
    {
		title: "Power Node Fragment 7",
        id: "PowerNodeFragment7",
        top: 58,
        left: 13,
    },
    {
		title: "Health Node 2",
        id: "HealthNode2",
        top: 58,
        left: 28,
    },
    {
		title: "Size Node 2",
        id: "SizeNode2",
        top: 61,
        left: 28,
    },
    {
		title: "Journal Page (Xedur)",
        id: "Note15",
        top: 62,
        left: 26,
    },
    {
		title: "Reply: The Outsider",
        id: "Note24",
        top: 60,
        left: 31,
    },
    {
		title: "Health Node Fragment 3",
        id: "HealthNodeFragment3",
        top: 61,
        left: 34,
    },
    {
		title: "Power Node 2",
        id: "PowerNode2",
        top: 63,
        left: 37,
    },
    {
		title: "Plan B",
        id: "Note14",
        top: 61,
        left: 20,
    },
    {
		title: "Forbidden Knowledge",
        id: "Note7",
        top: 65,
        left: 20,
    },
    {
		title: "Range Node 1",
        id: "RangeNode1",
        top: 62,
        left: 30,
    },
    {
		title: "Transcription",
        id: "Note16",
        top: 60,
        left: 15,
    },
    {
		title: "Power Node Fragment 3",
        id: "PowerNodeFragment3",
        top: 53,
        left: 20,
    },
    {
		title: "Drones",
        id: "Note28",
        top: 63,
        left: 32,
    },
    {
		title: "Health Node Fragment 6",
        id: "HealthNodeFragment6",
        top: 51,
        left: 30,
    },
    {
		title: "Power Node Fragment 5",
        id: "PowerNodeFragment5",
        top: 52,
        left: 22,
    },
    {
		title: "Power Node Fragment 6",
        id: "PowerNodeFragment6",
        top: 52,
        left: 23,
    },
    {
		title: "Inertial Pulse",
        id: "InertialPulse",
        top: 59,
        left: 37,
    },
    {
		title: "Range Node 4",
        id: "RangeNode4",
        top: 62,
        left: 20,
    },
    {
		title: "Power Node Fragment 9",
        id: "PowerNodeFragment9",
        top: 64,
        left: 35,
    },
    {
		title: "Power Node Fragment 4",
        id: "PowerNodeFragment4",
        top: 53,
        left: 21,
    },
    {
		title: "Data Bomb",
        id: "DataGrenade",
        top: 62,
        left: 16,
    },
    {
		title: "Security Notice",
        id: "Note10",
        top: 54,
        left: 45,
    },
    {
		title: "Health Node Fragment 14",
        id: "HealthNodeFragment14",
        top: 61,
        left: 43,
    },
    {
		title: "Modified Lab Coat",
        id: "GlitchTeleport",
        top: 52,
        left: 50,
    },
    {
		title: "Range Node 2",
        id: "RangeNode2",
        top: 62,
        left: 41,
    },
    {
		title: "Bioflux Accelerator 1",
        id: "TendrilsTop",
        top: 60,
        left: 40,
    },
    {
		title: "Health Node Fragment 7",
        id: "HealthNodeFragment7",
        top: 55,
        left: 47,
    },
    {
		title: "Size Node 3",
        id: "SizeNode3",
        top: 59,
        left: 46,
    },
    {
		title: "Health Node 3",
        id: "HealthNode3",
        top: 52,
        left: 47,
    },
    {
		title: "Health Node Fragment 5",
        id: "HealthNodeFragment5",
        top: 60,
        left: 48,
    },
    {
		title: "Password Tool",
        id: "PasswordTool",
        top: 63,
        left: 46,
    },
    {
		title: "Sudran Translation",
        id: "Note19",
        top: 63,
        left: 48,
    },
    {
		title: "English",
        id: "Note20",
        top: 56,
        left: 39,
    },
    {
		title: "Voranj",
        id: "Voranj",
        top: 57,
        left: 42,
    },
    {
		title: "Power Node Fragment 8",
        id: "PowerNodeFragment8",
        top: 59,
        left: 38,
    },
    {
		title: "Power Node Fragment 1",
        id: "PowerNodeFragment1",
        top: 51,
        left: 49,
    },
    {
		title: "Field Disruptor",
        id: "HighJump",
        top: 51,
        left: 57,
    },
    {
		title: "Firewall",
        id: "FireWall",
        top: 49,
        left: 56,
    },
    {
		title: "Power Node 3",
        id: "PowerNode3",
        top: 48,
        left: 52,
    },
    {
		title: "Remote Drone",
        id: "DroneGun",
        top: 39,
        left: 58,
    },
    {
		title: "Health Node Fragment 10",
        id: "HealthNodeFragment10",
        top: 48,
        left: 57,
    },
    {
		title: "Hypo-Atomizer",
        id: "VerticalSpread",
        top: 42,
        left: 57,
    },
    {
		title: "Health Node Fragment 8",
        id: "HealthNodeFragment8",
        top: 38,
        left: 55,
    },
    {
		title: "Address Disruptor 2",
        id: "AddressDisruptor2",
        top: 51,
        left: 53,
    },
    {
		title: "Health Node Fragment 9",
        id: "HealthNodeFragment9",
        top: 42,
        left: 58,
    },
    {
		title: "Health Node 4",
        id: "HealthNode4",
        top: 38,
        left: 61,
    },
    {
		title: "Grapple",
        id: "Grapple",
        top: 34,
        left: 68,
    },
    {
		title: "Tethered Charge",
        id: "TetheredCharge",
        top: 51,
        left: 61,
    },
    {
		title: "Public Notice",
        id: "Note13",
        top: 35,
        left: 60,
    },
    {
		title: "Health Node Fragment 12",
        id: "HealthNodeFragment12",
        top: 34,
        left: 61,
    },
    {
		title: "Health Node Fragment 11",
        id: "HealthNodeFragment11",
        top: 33,
        left: 68,
    },
    {
		title: "Power Node 4",
        id: "PowerNode4",
        top: 31,
        left: 68,
    },
    {
		title: "Journal Page (Uruku)",
        id: "Note17",
        top: 33,
        left: 56,
    },
    {
		title: "Power Node Fragment 14",
        id: "PowerNodeFragment14",
        top: 32,
        left: 56,
    },
    {
		title: "Reflector",
        id: "Reflect",
        top: 32,
        left: 63,
    },
    {
		title: "Enhanced Drone Launch",
        id: "EnhancedLaunch",
        top: 33,
        left: 62,
    },
    {
		title: "From the High Priestess",
        id: "Note12",
        top: 29,
        left: 59,
    },
    {
		title: "Ion Beam",
        id: "IonBeam",
        top: 39,
        left: 56,
    },
    {
		title: "Journal Page (Breach Pockets)",
        id: "Note25",
        top: 48,
        left: 18,
    },
    {
		title: "Athetos",
        id: "Note9",
        top: 47,
        left: 41,
    },
    {
		title: "Health Node Fragment 15",
        id: "HealthNodeFragment15",
        top: 49,
        left: 46,
    },
    {
		title: "Trenchcoat",
        id: "BlackCoat",
        top: 36,
        left: 25,
    },
    {
		title: "The Breach",
        id: "Note22",
        top: 42,
        left: 24,
    },
    {
		title: "Power Node Fragment 15",
        id: "PowerNodeFragment15",
        top: 39,
        left: 25,
    },
    {
		title: "Power Node Fragment 13",
        id: "PowerNodeFragment13",
        top: 34,
        left: 27,
    },
    {
		title: "Health Node Fragment 16",
        id: "HealthNodeFragment16",
        top: 32,
        left: 25,
    },
    {
		title: "Health Node 5",
        id: "HealthNode5",
        top: 35,
        left: 21,
    },
    {
		title: "My Lovely",
        id: "Note8",
        top: 32,
        left: 20,
    },
    {
		title: "The Outsider",
        id: "Note23",
        top: 42,
        left: 21,
    },
    {
		title: "Health Node Fragment 18",
        id: "HealthNodeFragment18",
        top: 43,
        left: 21,
    },
    {
		title: "Turbine Pulse",
        id: "TriCone",
        top: 27,
        left: 27,
    },
    {
		title: "Power Node Fragment 10",
        id: "PowerNodeFragment10",
        top: 44,
        left: 26,
    },
    {
		title: "Axiom 1",
        id: "Note18",
        top: 43,
        left: 42,
    },
    {
		title: "Vykhya Translation",
        id: "Note27",
        top: 42,
        left: 41,
    },
    {
		title: "Address Bomb",
        id: "GlitchBomb",
        top: 45,
        left: 45,
    },
    {
		title: "Power Node 5",
        id: "PowerNode5",
        top: 43,
        left: 45,
    },
    {
		title: "Health Node 6",
        id: "HealthNode6",
        top: 43,
        left: 44,
    },
    {
		title: "Range Node 3",
        id: "RangeNode3",
        top: 45,
        left: 39,
    },
    {
		title: "Shards",
        id: "Shards",
        top: 45,
        left: 36,
    },
    {
		title: "Oracca",
        id: "Note5",
        top: 42,
        left: 38,
    },
    {
		title: "Drone Teleport",
        id: "DroneTeleport",
        top: 36,
        left: 34,
    },
    {
		title: "Health Node Fragment 19",
        id: "HealthNodeFragment19",
        top: 39,
        left: 41,
    },
    {
		title: "Distortion Field",
        id: "DistortionField",
        top: 38,
        left: 42,
    },
    {
		title: "The Kuliltu",
        id: "Note4",
        top: 38,
        left: 37,
    },
    {
		title: "Health Node 7",
        id: "HealthNode7",
        top: 40,
        left: 35,
    },
    {
		title: "Power Node Fragment 17",
        id: "PowerNodeFragment17",
        top: 39,
        left: 37,
    },
    {
		title: "Bioflux Accelerator 2",
        id: "TendrilsBottom",
        top: 43,
        left: 34,
    },
    {
		title: "Health Node Fragment 20",
        id: "HealthNodeFragment20",
        top: 43,
        left: 30,
    },
    {
		title: "Anonymous Quote",
        id: "Note1",
        top: 29,
        left: 65,
    },
    {
		title: "The Land of Civilized Kings",
        id: "Note3",
        top: 28,
        left: 70,
    },
    {
		title: "Sudran Key",
        id: "BreachSuppressor",
        top: 27,
        left: 69,
    },
    {
		title: "Power Node 6",
        id: "PowerNode6",
        top: 26,
        left: 65,
    },
    {
		title: "Health Node Fragment 17",
        id: "HealthNodeFragment17",
        top: 42,
        left: 68,
    },
    {
		title: "Red Coat",
        id: "RedCoat",
        top: 45,
        left: 66,
    },
    {
		title: "Power Node Fragment 18",
        id: "PowerNodeFragment18",
        top: 46,
        left: 67,
    },
    {
		title: "Official Letter",
        id: "Note11",
        top: 33,
        left: 70,
    },
    {
		title: "Quantum Variegator",
        id: "Swim",
        top: 41,
        left: 66,
    },
    {
		title: "Health Node 8",
        id: "HealthNode8",
        top: 20,
        left: 22,
    },
    {
		title: "Power Node Fragment 11",
        id: "PowerNodeFragment11",
        top: 20,
        left: 24,
    },
    {
		title: "Proverb",
        id: "Note6",
        top: 21,
        left: 24,
    },
    {
		title: "Power Node Fragment 12",
        id: "PowerNodeFragment12",
        top: 21,
        left: 25,
    },
    {
		title: "Size Node 4",
        id: "SizeNode4",
        top: 16,
        left: 25,
    },
    {
		title: "Trace",
        id: "Note26",
        top: 14,
        left: 22,
    },
    {
		title: "Reverse Slicer",
        id: "Scythe",
        top: 16,
        left: 21,
    },
    {
		title: "Letter",
        id: "Note21",
        top: 9,
        left: 23,
    }
]
